// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCSGwxuP_nSnv5eGySCq5M89AE3GrZMB_4",
    authDomain: "flutterkt6-a6508.firebaseapp.com",
    projectId: "flutterkt6-a6508",
    storageBucket: "flutterkt6-a6508.firebasestorage.app",
    messagingSenderId: "527790756391",
    appId: "1:527790756391:web:cf009541b2bd826351f402",
    measurementId: "G-PLSZBFPLY4",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIbXCllesNHzacF-pyLalWkzX9iTxJMNo',
    appId: '1:527790756391:android:755e668f472abacd51f402',
    messagingSenderId: '527790756391',
    projectId: 'flutterkt6-a6508',
    storageBucket: 'flutterkt6-a6508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAouT86cY4AHfJ0ASIT39NPsvyPWS6uA64',
    appId: '1:527790756391:ios:2062deabbe272ec551f402',
    messagingSenderId: '527790756391',
    projectId: 'flutterkt6-a6508',
    storageBucket: 'flutterkt6-a6508.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAouT86cY4AHfJ0ASIT39NPsvyPWS6uA64',
    appId: '1:527790756391:ios:2062deabbe272ec551f402',
    messagingSenderId: '527790756391',
    projectId: 'flutterkt6-a6508',
    storageBucket: 'flutterkt6-a6508.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSGwxuP_nSnv5eGySCq5M89AE3GrZMB_4',
    appId: '1:527790756391:web:50ff617dc3b962b351f402',
    messagingSenderId: '527790756391',
    projectId: 'flutterkt6-a6508',
    authDomain: 'flutterkt6-a6508.firebaseapp.com',
    storageBucket: 'flutterkt6-a6508.firebasestorage.app',
    measurementId: 'G-E99DHTFD1W',
  );
}
